[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
check_untyped_defs = True
ignore_missing_imports = False 

[mypy-airtest.*,paddleocr.*,cv2.*,imutils.*]
ignore_missing_imports = True

[mypy-pixon.pixonwrapper]
disable_error_code = name-defined

[mypy-pages.game_page]
disable_error_code = attr-defined